### ISSUE TITLE
BeagleBone doesn't boot when CAN Backpack connected

### ISSUE THREAD

**Issue by sharrington93** [BuckeyeCurrent/BeagleBone-CAN-Backpack#18] opened 2015-04-27 05:02 UTC
@kimconcillado I added the headers to the board and tried it out after you left. It seemed to be causing the Beaglebone to not power up (this usually happens when it's trying to protect itself). 

Here's the issues and how I produced them:

1. Plugged the board in the working Beaglebone I have been using
2. Connected a CAN cable to the board and gave 12V power through CAN to the cape.

The power supply immediately went into overload mode. I then also tried powering the Beaglebone using the built in USB port but I didn't see any signs of power on the Beaglebone

I then removed the CAN cable and then tried powering just through the USB cable with the cape still plugged in. This time, the power LED on the beaglebone lit up but the Beaglebone failed to boot. I removed the cape and tried powering through the USB port and it booted up just fine. 

I expect the Beaglebone to power up through the built in USB port when the cape is plugged in and for the Beaglebone to also boot if there is power coming through the CAN.

**Comment by aaronbeekay** [comment] 2015-04-27 05:11
I tested this tonight but failed to reproduce.

## Short circuit test
### Procedure:
1. With the Cape disconnected from the BeagleBone, connect +12V through the CAN connector.
2. Observe the top and bottom sides of the PCB with the thermal camera.

### Observations:
- The Cape draws 0.23 A by the measurement on the front of the HP E3620A bench supply.
- Nothing heats up on either side of the board. On both sides, the highest temperature measured by the thermal camera was about 23º C, where I had handled the board.

### Notes: 
- Connecting +12V power through the CAN connector no longer powers the BeagleBone - +5V power comes from +12V_CONST now.

## Power functionality test
### Procedure
1. With the BeagleBone plugged into the CAN Cape, supply +12V and GND from the CAN connector. Also, connect pin 2 of X-521 (+12V_CONST) to +12V (same supply as the CAN supply).

### Observations
- The CAN Cape and the BeagleBone draw 0.105 A by the meter on the front of the supply.
- The "PWR" LED on the BeagleBone turns on. No other LEDs turn on.

### Notes
- I just pulled a random BeagleBone out of the box - I don't know if it has to be programmed for the activity LEDs to light up.

Hope this helps.

**Comment by sharrington93** [comment] 2015-04-27 05:15
@aaronbeekay For the power functionality test, the four other LEDs should flash if all is well. If you pulled a new Beaglebone and tested with it, the four LEDs should have been flashing too because they come preprogrammed.

**Comment by sharrington93** [comment] 2015-04-28 01:10
## LED Testing

### Procedure
1. Plug CAN Cape into Beaglebone. Beaglebone powered up and running.
2. Supply 12V to 12V Constant plug. 
3. Triggered GPIOs 2_12, 2_10, 2_8, 2_6 to go high.
4. Plugged the LED cables into the CAN cape and connected cable leads to the LEDs.

### Expected Behavior
For the LEDs to turn on.

### Observations
* LEDs did not turn on.
* The GPIOs were checked to see if they were actually high. All were checked and measured 3.3V.
* I checked the voltage between the ground lead and each output lead on the LED cable. It measured 30 mV.

**Comment by sharrington93** [comment] 2015-04-28 01:21
## CAN Testing

### Procedure
1. Plug CAN Cape into Beaglebone Black
2. Enabled CAN on the Beaglebone.
3. Connected Kvaser to the CAN cape and Kvaser to computer.
4. Sent CAN data from computer to CAN cape.

### Expected Behavior
Nice data incoming on the Beaglebone Black

### Observations
No sign of CAN data on Beaglebone Black.
Error frames on the computer side.

### Notes
I plugged in the old CAN cape from RW-2x afterwards and followed the same procedure. I saw CAN on the Beaglebone Black

**Comment by sharrington93** [comment] 2015-04-28 01:37
## LED Testing

LEDs light up but they always light up regardless of whether I tell the GPIO to output high or low.

**Comment by sharrington93** [comment] 2015-04-28 01:47
@aaronbeekay You are right about the power LED lighting up but the Beaglebone will not boot up if the cape is plugged in on boot up. If I remove the cape, start up the Beaglebone, and then plug in the cape, it seems to be ok.

**Comment by aaronbeekay** [comment] 2015-04-28 02:07
Let's move the CAN issues to a new issue - I made #19

**Comment by aaronbeekay** [comment] 2015-05-02 22:51
The boot issues seem like they're due to the SYS_BOOT pins on the BeagleBone being used to control the LEDs on the Cape. Specifically, the LED control signals are connected:

LED signal     |     Expansion header pin     |     BeagleBone signal name | BeagleBone boot | Bias on BB
------------        |    --------------------------------- |    --------------------------- | ---- | ----- |
LED2_R_SW | P8-45 | LCD_DATA0 | SYS_BOOT0 | Pulled down
LED2_G_SW | P8-43 | LCD_DATA2 |SYS_BOOT2 | **Pulled up**
LED1_R_FF | P8-41 | LCD_DATA4 | SYS_BOOT4 | **Pulled up**
LED1_G_FF | P8-39 | LCD_DATA6 | SYS_BOOT6 | Pulled down

These pins are pulled down on the Cape with 10k resistors. Section 8.3.1 of the BeagleBone System Reference Manual, "Boot Pins", warns against pulling these resistors up or down on the board.

The offending pulldown resistors R12 and R15, on LED2_G_SW and LED1_R_FF. As a temporary fix, we can change these resistors to DNP, and remove them from the board we have built. 

Because of this change, when the BeagleBone initially starts up, the "SW" indicator will be green, and the "FF" indicator will be red, until the BeagleBone boots up far enough to drive the pins.

**Comment by aaronbeekay** [comment] 2015-05-15 02:41
This issue is fixed in v2.3.1 because the LED pins have been moved away from the boot pins. The working version of v2.3 has been modified to include the fix from v2.3.1.

**Closed by aaronbeekay** 2015-05-15 02:41 UTC
